#############################贡献内容请勿更改以下配置#######################################################
site_name: Notes at SJTU

repo_url: https://github.com/felixchen0707/sjtu-notes
repo_name: felixchen0707/sjtu-notes
edit_uri: "edit/mkdocs/docs/"

theme:
  name: material
  custom_dir: overrides


  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: 'Noto Sans SC'
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  icon:
    logo: logo
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.indexes
    # - navigation.sections
    # - navigation.expand  # 默认情况下不要展开，防止文章数量过多
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top  # 返回顶部
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

# MarkDown扩展
markdown_extensions:
  # 缩写支持
  - abbr

  # 列表支持
  - def_list

  # 脚注支持
  - footnotes

  # html代码支持
  - md_in_html

  # 目录支持
  - toc:
      permalink: ⚓︎

  # 表格支持
  - tables

  # 数学公式
  - pymdownx.arithmatex:
      generic: true

  # 加粗、斜体等支持
  - pymdownx.betterem

  # 高亮、下划线、删除线
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # 代码块支持
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences

  # tab支持
  - pymdownx.tabbed:
      alternate_style: true

  # 行内代码
  - pymdownx.inlinehilite

  # 任务单支持
  - pymdownx.tasklist:
      custom_checkbox: true
  
  # 键盘支持
  - pymdownx.keys

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/tex-mml-chtml.js
  - assets/javascripts/polyfill.min.js

  # - assets/javascripts/input/tex/extensions/action.js
  # - assets/javascripts/input/tex/extensions/all-packages.js
  # - assets/javascripts/input/tex/extensions/ams.js
  # - assets/javascripts/input/tex/extensions/amscd.js
  # - assets/javascripts/input/tex/extensions/autoload.js
  # - assets/javascripts/input/tex/extensions/bbox.js
  - assets/javascripts/input/tex/extensions/boldsymbol.js
  # - assets/javascripts/input/tex/extensions/braket.js
  # - assets/javascripts/input/tex/extensions/bussproofs.js
  # - assets/javascripts/input/tex/extensions/cancel.js
  # - assets/javascripts/input/tex/extensions/cases.js
  # - assets/javascripts/input/tex/extensions/centernot.js
  - assets/javascripts/input/tex/extensions/color.js
  - assets/javascripts/input/tex/extensions/colortbl.js
  - assets/javascripts/input/tex/extensions/colorv2.js
  # - assets/javascripts/input/tex/extensions/configmacros.js
  # - assets/javascripts/input/tex/extensions/empheq.js
  # - assets/javascripts/input/tex/extensions/enclose.js
  # - assets/javascripts/input/tex/extensions/extpfeil.js
  # - assets/javascripts/input/tex/extensions/gensymb.js
  # - assets/javascripts/input/tex/extensions/html.js
  # - assets/javascripts/input/tex/extensions/mathtools.js
  # - assets/javascripts/input/tex/extensions/mhchem.js
  # - assets/javascripts/input/tex/extensions/newcommand.js
  # - assets/javascripts/input/tex/extensions/noerrors.js
  # - assets/javascripts/input/tex/extensions/noundefined.js
  # - assets/javascripts/input/tex/extensions/physics.js
  # - assets/javascripts/input/tex/extensions/require.js
  # - assets/javascripts/input/tex/extensions/setoptions.js
  # - assets/javascripts/input/tex/extensions/tagformat.js
  # - assets/javascripts/input/tex/extensions/textcomp.js
  # - assets/javascripts/input/tex/extensions/textmacros.js
  # - assets/javascripts/input/tex/extensions/unicode.js
  # - assets/javascripts/input/tex/extensions/upgreek.js
  # - assets/javascripts/input/tex/extensions/verb.js



plugins:
  - glightbox # 点击图片放大
  - search: # 搜索插件
  - git-revision-date-localized:
      enable_creation_date: true # 显示创建和最后一次更新日期


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/felixchen0707/sjtu-iBME

copyright: Copyright &copy; Since 2022 sjtu-notes contributors

#####################################如果您是贡献内容，请不要随意更改以上的配置###############################

# 全站导航栏
nav:
  - 开始:
    - index.md
    
  - 课程:
    - 大一课程:
      - MATH1201 高等数学I:
        - courses/grade1/MATH1201/MATH1201_01.md
      - MATH1203 数学分析I:
        - courses/grade1/MATH1203/MATH1203_01.md
      - MATH1607H 数学分析(荣誉)I:
        - courses/grade1/MATH1607H/MATH1607H_01.md
      - MATH1202 高等数学II:
        - courses/grade1/MATH1202/MATH1202_01.md
      - MATH1204 数学分析II:
        - courses/grade1/MATH1204/MATH1204_01.md
      - MATH1608H 数学分析(荣誉)II:
        - courses/grade1/MATH1608H/MATH1608H_01.md
      - MATH1205 线性代数:
        - courses/grade1/MATH1205/MATH1205_01.md
      - MATH1207 概率统计:
        - courses/grade1/MATH1207/MATH1207_01.md
      - CS1501 程序设计思想与方法(C++):
        - courses/grade1/CS1501/CS1501_01.md
      - CS0501 数据结构:
        - courses/grade1/CS0501/CS0501_01.md
      - PHY1251 大学物理(A类)I:
        - courses/grade1/PHY1251/PHY1251_01.md
      - PHY1251 大学物理(荣誉)I:
        - courses/grade1/PHY1251H/PHY1251H_01.md
    - 大二课程:
      - EE0501 电路理论:
        - courses/grade2/EE0501/EE0501_01.md
      - EST2501 数字电子技术:
        - courses/grade2/EST2501/EST2501_01.md
      - MECH2508 理论力学:
        - courses/grade2/MECH2508/MECH2508_01.md
      - MATH1206 数理方法:
        - courses/grade2/MATH1206/MATH1206_01.md
      - BME1201 生物医学工程导论:
        - courses/grade2/BME1201/BME1201_01.md
      - BME1203 生物学导论:
        - courses/grade2/BME1203/BME1203_01.md
      - BME2301 生物医学信号与系统(1):
        - courses/grade2/BME2301/BME2301_01.md
      - BME2201 生物医学统计概论:
        - courses/grade2/BME2201/BME2201_01.md
      - BME2402 细胞生物学:
        - courses/grade2/BME2402/BME2402_01.md
      - CHEM2204 有机化学(B类):
        - courses/grade2/CHEM2204/CHEM2204_01.md
      - BME2302 医学物理导论:
        - courses/grade2/BME2302/BME2302_01.md
      - BME2401 材料科学与工程基础:
        - courses/grade2/BME2401/BME2401_01.md
      - BME2304 模拟电子技术与实验:
        - courses/grade2/BME2304/BME2304_01.md

  - 课程笔记:
    - 大二年级:
      - 大学物理(A类，荣誉)II:
        - notes/grade2/PHY1252/001.md
        - notes/grade2/PHY1252/002.md
        - notes/grade2/PHY1252/003.md
      - 电路理论:
        - notes/grade2/EE0501/001.md
        - notes/grade2/EE0501/002.md
        - notes/grade2/EE0501/003.md
      - 数理方法:
        - notes/grade2/MATH1206/001.md
        - notes/grade2/MATH1206/002.md
      - 理论力学:
        - notes/grade2/MECH2508/001.md
        - notes/grade2/MECH2508/002.md
      - 数字电子技术:
        - notes/grade2/EST2501/001.md
        - notes/grade2/EST2501/002.md



  - 关于:
    - about/contribute.md
    - about/discussion.md
    - about/contact.md
